require:
  - rubocop-rspec
  - rubocop-rails

AllCops:
  Exclude:
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'config/**/*'
    - 'bin/**/*'
    - '*'

Rails/UniqueValidationWithoutIndex:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Rails/NotNullColumn:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: never

RSpec/MultipleMemoizedHelpers:
  Max: 10

Metrics/MethodLength:
  Max: 15

Metrics/ParameterLists:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'config/routes.rb'

Rails/UnknownEnv:
  Environments:
    - production
    - test
    - development
