default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  socket: /tmp/mysql.sock

test:
  <<: *default
  database: ping_pong_teams_test
  username: <%= ENV.fetch("MYSQL_USER", "root") %>
  password: <%= ENV.fetch("MYSQL_PASSWORD", "") %>
  host: <%= ENV.fetch('MYSQL_HOST', 'db') %>
  port: <%= ENV.fetch('MYSQL_PORT', 3306) %>
